apiVersion: v2
name: basic-web-app
description: a generic helm chart to run basic web applications in kubernertes
type: application
version: 1.0.1
icon: https://itsmethemojo.github.io/helm-charts/icon.png
