apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "basic-web-app.fullname" . }}
  labels:
    {{- include "basic-web-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "basic-web-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with include "basic-web-app.podAnnotations" . }}
      annotations:
        {{- . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "basic-web-app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "basic-web-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tagPrefix }}{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "basic-web-app.fullname" $ }}-env
                  key: {{ $key }}
                  optional: false
            {{- end }}
            {{- range .Values.envFromExternalSecret }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secret }}
                  key: {{ .key }}
                  optional: false
            {{- end }}
          {{- with .Values.persistentVolumeClaims }}
          volumeMounts:
            {{- range . }}
            - mountPath: {{ .mountPath }}
              name: {{ include "basic-web-app.fullname" $ }}-{{ .name }}
            {{- end }}
          {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.persistentVolumeClaims }}
      volumes:
        {{- range . }}
        - name: {{ include "basic-web-app.fullname" $ }}-{{ .name }}
          persistentVolumeClaim:
            claimName: {{ include "basic-web-app.fullname" $ }}-{{ .name }}
        {{- end }}
      {{- end }}
