{{- if .Values.env -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "basic-web-app.fullname" . }}-env-vars
  labels:
    {{- include "basic-web-app.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
