{{- if .Values.env -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "basic-web-app.fullname" . }}-env
  labels:
    {{- include "basic-web-app.labels" . | nindent 4 }}
stringData:
  {{- toYaml .Values.env | nindent 2 }}
{{- end }}
